FROM php:8.1-apache

ENV GRAV_VERSION 1.7.44

# Update system
RUN apt-get update

# Install dependencies
RUN apt-get install -y libzip-dev libpng-dev libjpeg-dev unzip rsync gosu

# Configure and install PHP extensions
RUN docker-php-ext-configure gd --with-jpeg
RUN docker-php-ext-install zip gd

WORKDIR /var/www
RUN curl -o grav-admin.zip -SL https://getgrav.org/download/core/grav-admin/${GRAV_VERSION} && \
    unzip -qq grav-admin.zip -d /usr/share && \
    rm grav-admin.zip
    
RUN chown -R www-data:www-data /usr/share/grav-admin
                    
COPY entrypoint.sh /entrypoint.sh

# Enable mod_rewrite for Apache
RUN a2enmod rewrite

USER www-data
RUN cd /usr/share/grav-admin &&  \
    bin/gpm install devtools

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
