services:
  grav:
    build:
      context: .
      dockerfile: Dockerfile_dev
    user: root
    environment:
      - INGRID_API=https://api.dev.informationgrid.eu/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:80"
    network_mode: bridge
    volumes:
      - ./develop/admin.yaml:/var/www/html/user/accounts/admin.yaml
      - ./user/themes:/var/www/html/user/themes
      - ./user/pages:/var/www/html/user/pages
      - ./user/plugins:/var/www/html/user/plugins
      - ./user/blueprints:/var/www/html/user/blueprints
      - ./data:/var/www/html/user/data
      - ./logs:/var/www/html/logs
      - ./develop/config:/var/www/html/user/localhost/config
      - ./system:/var/www/html/system
