home:
    categories:
        facet_config: [
            {
                "id": "type",
                "facets": {
                    "metadata": {
                        "icon": "ic-metadata",
                        "query": {
                            "filter": {
                                "term": {
                                    "datatype": "metadata"
                                }
                            }
                        },
                    },
                    "inspire": {
                        "icon": "ic-inspire",
                        "query": {
                            "filter": {
                                "bool": {
                                    "should": [
                                        {
                                            "term": {
                                                "t04_search.searchterm": "inspire"
                                            }
                                        },
                                        {
                                            "term": {
                                                "t04_search.searchterm": "inspireidentifiziert"
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "opendata": {
                        "icon": "ic-opendata",
                        "query": {
                            "filter": {
                                "bool": {
                                    "should": [
                                        {
                                            "term": {
                                                "t04_search.searchterm": "opendata"
                                            }
                                        },
                                        {
                                            "term": {
                                                "t04_search.searchterm": "opendataident"
                                            }
                                        }
                                    ]
                                }
                            }
                        },
                    },
                    "maps": {
                        "icon": "ic-map",
                        "query": {
                            "filter": {
                                "wildcard": {
                                    "capabilities_url": "http*"
                                }
                            }
                        },
                    },
                }
            }
        ]
hit_search:
    facet_config: [
        {
            "id": "type",
            "open": true,
            "facets": {
                "job": {
                    "codelist": "8000",
                    "codelist_entry_id": "0",
                    "query": {
                        "filter": {
                            "term": {
                                "t01_object.obj_class": "0"
                            }
                        }
                    },
                },
                "service": {
                    "codelist": "8000",
                    "codelist_entry_id": "6",
                    "query": {
                        "filter": {
                            "term": {
                                "t01_object.obj_class": "6"
                            }
                        }
                    },
                },
                "geodata": {
                    "codelist": "8000",
                    "codelist_entry_id": "1",
                    "query": {
                        "filter": {
                            "term": {
                                "t01_object.obj_class": "1"
                            }
                        }
                    },
                },
                "document": {
                    "codelist": "8000",
                    "codelist_entry_id": "2",
                    "query": {
                        "filter": {
                            "term": {
                                "t01_object.obj_class": "2"
                            }
                        }
                    },
                },
                "geoservice": {
                    "codelist": "8000",
                    "codelist_entry_id": "3",
                    "query": {
                        "filter": {
                            "term": {
                                "t01_object.obj_class": "3"
                            }
                        }
                    },
                },
                "database": {
                    "codelist": "8000",
                    "codelist_entry_id": "5",
                    "query": {
                        "filter": {
                            "term": {
                                "t01_object.obj_class": "5"
                            }
                        }
                    },
                },
                "inspire": {
                    "query": {
                        "filter": {
                            "bool": {
                                "should": [
                                    {
                                        "term": {
                                            "t04_search.searchterm": "inspire"
                                        }
                                    },
                                    {
                                        "term": {
                                            "t04_search.searchterm": "inspireidentifiziert"
                                        }
                                    }
                                ]
                            }
                        }
                    }
                },
                "opendata": {
                    "query": {
                        "filter": {
                            "bool": {
                                "should": [
                                    {
                                        "term": {
                                            "t04_search.searchterm": "opendata"
                                        }
                                    },
                                    {
                                        "term": {
                                            "t04_search.searchterm": "opendataident"
                                        }
                                    }
                                ]
                            }
                        }
                    },
                },
                "hvd": {
                    "query": {
                        "filter": {
                            "term": {
                                "is_hvd": "true"
                            }
                        }
                    },
                },
                "maps": {
                    "query": {
                        "filter": {
                            "wildcard": {
                                "capabilities_url": "http*"
                            }
                        }
                    },
                }
            }
        },
        {
            "id": "provider",
            "codelist": "111",
            "list_limit": 6,
            "query": {
                "terms": {
                    "field": "provider",
                    "min_doc_count": 0
                }
            },
            "search": "provider:%s"
        },
        {
            "id": "bbox",
            "filter": "{\"bool\": {\"should\": [{\"nested\": {\"path\": \"spatial\",\"query\": {\"bool\": {\"must\": [{\"geo_bounding_box\": {\"spatial.geometries\": {\"top_left\": [%f,%f],\"bottom_right\": [%f,%f]}}},{\"exists\": {\"field\": \"spatial.geometries\"}}]}}}},{\"bool\": {\"must\": [{\"range\": {\"x1\": {\"gte\": %f}}},{\"range\": {\"y2\": {\"lte\": %f}}},{\"range\": {\"y1\": {\"gte\": %f}}},{\"range\": {\"x2\": {\"lte\": %f}}}],\"must_not\":{\"nested\":{\"path\":\"spatial\",\"query\":{\"bool\":{\"must\":[{\"exists\":{\"field\":\"spatial.geometries\"}}]}}}}}}],\"minimum_should_match\": 1}}"
        }
    ]
