home:
    categories:
        facet_config: [
            {
                "id": "type",
                "facets": {
                    "www": {
                        "icon": "ic-www",
                        "query": {
                            "filter": {
                                "term": {
                                    "datatype": "www"
                                }
                            }
                        },
                    },
                    "metadata": {
                        "icon": "ic-metadata",
                        "query": {
                            "filter": {
                                "term": {
                                    "datatype": "metadata"
                                }
                            }
                        },
                    },
                    "inspire": {
                        "icon": "ic-inspire",
                        "query": {
                            "filter": {
                                "bool": {
                                    "should": [
                                        {
                                            "term": {
                                                "t04_search.searchterm": "inspire"
                                            }
                                        },
                                        {
                                            "term": {
                                                "t04_search.searchterm": "inspireidentifiziert"
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "opendata": {
                        "icon": "ic-opendata",
                        "query": {
                            "filter": {
                                "bool": {
                                    "should": [
                                        {
                                            "term": {
                                                "t04_search.searchterm": "opendata"
                                            }
                                        },
                                        {
                                            "term": {
                                                "t04_search.searchterm": "opendataident"
                                            }
                                        }
                                    ]
                                }
                            }
                        },
                    },
                    "maps": {
                        "icon": "ic-map",
                        "query": {
                            "filter": {
                                "wildcard": {
                                    "capabilities_url": "http*"
                                }
                            }
                        },
                    },
                }
            },{
                "id": "provider",
                "label": "Bundesländern",
                "facets": {
                    "bw": {
                        "icon": "images/partner/svg/bw.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "bw"
                                }
                            }
                        },
                    },
                    "by": {
                        "icon": "images/partner/svg/by.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "by"
                                }
                            }
                        },
                    },
                    "be": {
                        "icon": "images/partner/svg/be.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "be"
                                }
                            }
                        },
                    },
                    "bb": {
                        "icon": "images/partner/svg/bb.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "bb"
                                }
                            }
                        },
                    },
                    "hb": {
                        "icon": "images/partner/svg/hb.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "hb"
                                }
                            }
                        },
                    },
                    "hh": {
                        "icon": "images/partner/svg/hh.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "hh"
                                }
                            }
                        },
                    },
                    "he": {
                        "icon": "images/partner/svg/he.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "he"
                                }
                            }
                        },
                    },
                    "mv": {
                        "icon": "images/partner/svg/mv.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "mv"
                                }
                            }
                        },
                    },
                    "ni": {
                        "icon": "images/partner/svg/ni.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "ni"
                                }
                            }
                        },
                    },
                    "nw": {
                        "icon": "images/partner/svg/nw.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "nw"
                                }
                            }
                        },
                    },
                    "rp": {
                        "icon": "images/partner/svg/rp.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "rp"
                                }
                            }
                        },
                    },
                    "sl": {
                        "icon": "images/partner/svg/sl.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "sl"
                                }
                            }
                        },
                    },
                    "sn": {
                        "icon": "images/partner/svg/sn.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "sn"
                                }
                            }
                        },
                    },
                    "st": {
                        "icon": "images/partner/svg/st.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "st"
                                }
                            }
                        },
                    },
                    "sh": {
                        "icon": "images/partner/svg/sh.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "sh"
                                }
                            }
                        },
                    },
                    "th": {
                        "icon": "images/partner/svg/th.svg",
                        "codelist": "110",
                        "query": {
                            "filter": {
                                "term": {
                                    "partner": "th"
                                }
                            }
                        },
                    },
                }
            },
        ]
hit_search:
    facet_config: [
        {
            "id": "type",
            "open": true,
            "facets": {
                "inspire": {
                    "query": {
                        "filter": {
                            "bool": {
                                "should": [
                                    {
                                        "term": {
                                            "t04_search.searchterm": "inspire"
                                        }
                                    },
                                    {
                                        "term": {
                                            "t04_search.searchterm": "inspireidentifiziert"
                                        }
                                    }
                                ]
                            }
                        }
                    }
                },
                "opendata": {
                    "query": {
                        "filter": {
                            "bool": {
                                "should": [
                                    {
                                        "term": {
                                            "t04_search.searchterm": "opendata"
                                        }
                                    },
                                    {
                                        "term": {
                                            "t04_search.searchterm": "opendataident"
                                        }
                                    }
                                ]
                            }
                        }
                    },
                },
                "hvd": {
                    "query": {
                        "filter": {
                            "term": {
                                "is_hvd": "true"
                            }
                        }
                    },
                },
                "adv": {
                    "query": {
                        "filter": {
                            "bool": {
                                "should": [
                                    {
                                        "term": {
                                            "t04_search.searchterm": "AdVMIS"
                                        }
                                    },
                                    {
                                        "term": {
                                            "t04_search.searchterm": "AdV"
                                        }
                                    }
                                ]
                            }
                        }
                    },
                },
                "maps": {
                    "query": {
                        "filter": {
                            "wildcard": {
                                "capabilities_url": "http*"
                            }
                        }
                    },
                },
                "metadata": {
                    "display_sort_hits_on_selection": true,
                    "query": {
                        "filter": {
                            "term": {
                                "datatype": "metadata"
                            }
                        }
                    },
                },
                "www": {
                    "query": {
                        "filter": {
                            "term": {
                                "datatype": "www"
                            }
                        }
                    },
                },
            }
        },
        {
            "id": "metadata_group",
            "open_by": {
                "type": "metadata",
            },
            "display_sort_hits_on_selection": true,
            "codelist": "8000",
            "query": {
                "terms": {
                    "field": "t01_object.obj_class",
                    "exclude": "1000",
                    "min_doc_count": 0
                }
            },
            "search": "t01_object.obj_class:%d"
        },
        {
            "id": "modtime",
            "display_depend_on": {
                "type": "metadata",
                "metadata_group": "",
            },
            "facets": {
                "last_month": {
                    "query": {
                        "filter": {
                            "range": {
                                "modified": {
                                    "gte": "now-1M"
                                }
                            }
                        }
                    }
                },
                "last_three_month": {
                    "query": {
                        "filter": {
                            "range": {
                                "modified": {
                                    "gte": "now-3M"
                                }
                            }
                        }
                    }
                },
                "last_year": {
                    "query": {
                        "filter": {
                            "range": {
                                "modified": {
                                    "gte": "now-1y"
                                }
                            }
                        }
                    }
                },
                "last_five_years": {
                    "query": {
                        "filter": {
                            "range": {
                                "modified": {
                                    "gte": "now-5y"
                                }
                            }
                        }
                    }
                },
                "older_five_years": {
                    "query": {
                        "filter": {
                            "range": {
                                "modified": {
                                    "lte": "now-5y"
                                }
                            }
                        }
                    }
                }
            }
        },
        {
            "id": "provider",
            "codelist": "110",
            "extend_facet_selection_config": {
                "field": "provider",
                "list_limit": 6,
                "sort": "name"
            },
            "sort": "name",
            "query": {
                "terms": {
                    "field": "partner",
                    "min_doc_count": 0
                }
            },
            "search": "partner:%s"
        },
        {
            "id": "bbox",
            "filter": "{\"bool\": {\"should\": [{\"nested\": {\"path\": \"spatial\",\"query\": {\"bool\": {\"must\": [{\"geo_bounding_box\": {\"spatial.geometries\": {\"top_left\": [%f,%f],\"bottom_right\": [%f,%f]}}},{\"exists\": {\"field\": \"spatial.geometries\"}}]}}}},{\"bool\": {\"must\": [{\"range\": {\"x1\": {\"gte\": %f}}},{\"range\": {\"y2\": {\"lte\": %f}}},{\"range\": {\"y1\": {\"gte\": %f}}},{\"range\": {\"x2\": {\"lte\": %f}}}],\"must_not\":{\"nested\":{\"path\":\"spatial\",\"query\":{\"bool\":{\"must\":[{\"exists\":{\"field\":\"spatial.geometries\"}}]}}}}}}],\"minimum_should_match\": 1}}"
        }
    ]