home:
    hits:
        requested_fields:
        source:
            include:
            exclude:
                - content
                - idf
        query_string_operator: AND
    categories:
        facet_config: [
            {
                "id": "type",
                "facets": {
                    "metaclass_map": {
                        "label": "Geodatensatz",
                        "icon": "ic-earth",
                        "display_on_empty": true,
                        "query": {
                            "filter": {
                                "term": {
                                    "t01_object.obj_class": 1
                                }
                            }
                        }
                    },
                    "download-wfs": {
                        "label": "Downloaddienst WFS",
                        "icon": "ic-download",
                        "display_on_empty": true,
                        "query": {
                            "filter": {
                                "match": {
                                    "t011_obj_serv_version.version_value": "OGC:WFS"
                                }
                            }
                        }
                    },
                    "map-wms": {
                        "label": "Darstellungsdienst WMS",
                        "icon": "ic-maps",
                        "display_on_empty": true,
                        "query": {
                            "filter": {
                                "match": {
                                    "t011_obj_serv_version.version_value": "OGC:WMS"
                                }
                            }
                        }
                    },
                    "inspire": {
                        "icon": "ic-inspire",
                        "display_on_empty": true,
                        "query": {
                            "filter": {
                                "bool": {
                                    "should": [
                                        {
                                            "term": {
                                                "t04_search.searchterm": "inspire"
                                            }
                                        },
                                        {
                                            "term": {
                                                "t04_search.searchterm": "inspireidentifiziert"
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "opendata": {
                        "icon": "ic-opendata",
                        "display_on_empty": true,
                        "query": {
                            "filter": {
                                "bool": {
                                    "should": [
                                        {
                                            "term": {
                                                "t04_search.searchterm": "opendata"
                                            }
                                        },
                                        {
                                            "term": {
                                                "t04_search.searchterm": "opendataident"
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "udo-data": {
                        "label": "Umwelt-Daten und -Karten Online",
                        "icon": "ic-leaf",
                        "display_on_empty": true,
                        "query": {
                            "filter": {
                                "bool": {
                                    "should": [
                                        {
                                            "wildcard": {
                                                "t017_url_ref.url_link": "*udo.*"
                                            }
                                        },
                                        {
                                            "wildcard": {
                                                "t017_url_ref.url_link": "*umweltdaten.*"
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        ]
hit_search:
    facet_config: [
        {
            "id": "type",
            "open": true,
            "selection_single": true,
            "facets": {
                "metaclass_map": {
                    "label": "Geodatensatz",
                    "query": {
                        "filter": {
                            "term": {
                                "t01_object.obj_class": 1
                            }
                        }
                    }
                },
                "download-wfs": {
                    "label": "Downloaddienst WFS",
                    "query": {
                        "filter": {
                            "match": {
                                "t011_obj_serv_version.version_value": "OGC:WFS"
                            }
                        }
                    }
                },
                "download-atom": {
                    "label": "Downloaddienst ATOM-Feed",
                    "query": {
                        "filter": {
                            "match": {
                                "t011_obj_serv_version.version_value": "ATOM"
                            }
                        }
                    }
                },
                "map-wms": {
                    "label": "Darstellungsdienst WMS",
                    "query": {
                        "filter": {
                            "match": {
                                "t011_obj_serv_version.version_value": "OGC:WMS"
                            }
                        }
                    }
                },
                "map-wmts": {
                    "label": "Darstellungsdienst WMTS",
                    "query": {
                        "filter": {
                            "match": {
                                "t011_obj_serv_version.version_value": "OGC:WMTS"
                            }
                        }
                    }
                },
                "inspire": {
                    "query": {
                        "filter": {
                            "bool": {
                                "should": [
                                    {
                                        "term": {
                                            "t04_search.searchterm": "inspire"
                                        }
                                    },
                                    {
                                        "term": {
                                            "t04_search.searchterm": "inspireidentifiziert"
                                        }
                                    }
                                ]
                            }
                        }
                    }
                },
                "opendata": {
                    "query": {
                        "filter": {
                            "bool": {
                                "should": [
                                    {
                                        "term": {
                                            "t04_search.searchterm": "opendata"
                                        }
                                    },
                                    {
                                        "term": {
                                            "t04_search.searchterm": "opendataident"
                                        }
                                    }
                                ]
                            }
                        }
                    }
                },
                "hvd": {
                    "label": "HVD",
                    "query": {
                        "filter": {
                            "term": {
                                "is_hvd": true
                            }
                        }
                    }
                },
                "udo-data": {
                    "label": "Umwelt-Daten und -Karten Online",
                    "query": {
                        "filter": {
                            "bool": {
                                "should": [
                                    {
                                        "wildcard": {
                                            "t017_url_ref.url_link": "*udo.*"
                                        }
                                    },
                                    {
                                        "wildcard": {
                                            "t017_url_ref.url_link": "*umweltdaten.*"
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        {
            "id": "distributor",
            "label": "Vertrieb der Geodaten",
            "selection_single": true,
            "query": {
                "terms": {
                    "field": "distributor",
                    "min_doc_count": 0
                }
            },
            "search": "distributor:%s"
        },
        {
            "id": "metadata_tree",
            "label": "Fachthemen",
            "selection_single": true,
            "catalog": {
                "ident": "bw"
            }
        }
    ]
    requested_fields:
        - t04_search.searchterm
        - t017_url_ref.url_link
        - t017_url_ref.content
        - t017_url_ref.special_ref
        - t017_url_ref.datatype
        - object_reference.obj_uuid
        - object_reference.obj_name
        - object_reference.obj_class
        - object_reference.type
        - object_reference.version
        - refering.object_reference.obj_uuid
        - refering.object_reference.obj_name
        - refering.object_reference.obj_class
        - refering.object_reference.type
        - refering.object_reference.version
    source:
        include:
        exclude:
            - content
            - idf
    query_string_operator: AND
hit_detail:
    requested_fields:
        - partner
        - provider
        - t03_catalogue.cat_name
    source:
        include:
            - idf
            - dataSourceName
            - iPlugId
            - title
        exclude:
            - content
    query_string_operator: AND