form:
  fields:
    upload.section:
      type: section
      title: THEME.ADMIN.UPLOAD.TITLE
      underline: true

    upload.portals:
      type: file
      label: THEME.ADMIN.UPLOAD.PORTALS.TITLE
      destination: 'theme://assets/upload/portals'
      multiple: true
      limit: 0
      autofocus: false
      accept:
        - image/*