form:
  fields:
    hit_detail.section:
      type: section
      title: THEME.ADMIN.HIT_DETAIL.TITLE
      underline: true

    hit_detail.query_string_operator:
      type: toggle
      label: THEME.ADMIN.HIT_DETAIL.QUERY_STRING_OPERATOR.LABEL
      help: THEME.ADMIN.HIT_DETAIL.QUERY_STRING_OPERATOR.HELP
      highlight: AND
      options:
        "AND": AND
        "OR": OR
      validate:
        type: text

    hit_detail.display_use_constraints_json:
      type: toggle
      label: THEME.ADMIN.HIT_DETAIL.DISPLAY_USE_CONSTRAINTS_JSON.LABEL
      help: THEME.ADMIN.HIT_DETAIL.DISPLAY_USE_CONSTRAINTS_JSON.HELP
      highlight: 1
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: text

    hit_detail.requested_fields:
      type: selectize
      label: THEME.ADMIN.HIT_DETAIL.REQUESTED_FIELDS.LABEL
      help: THEME.ADMIN.HIT_DETAIL.REQUESTED_FIELDS.HELP
      validate:
        type: commalist

    hit_detail.source.include:
      type: selectize
      label: THEME.ADMIN.HIT_DETAIL.SOURCE.INCLUDE.LABEL
      help: THEME.ADMIN.HIT_DETAIL.SOURCE.INCLUDE.HELP
      validate:
        type: commalist

    hit_detail.source.exclude:
      type: selectize
      label: THEME.ADMIN.HIT_DETAIL.SOURCE.EXCLUDE.LABEL
      help: THEME.ADMIN.HIT_DETAIL.SOURCE.EXCLUDE.HELP
      validate:
        type: commalist

    hit_detail.summary_replace_newline:
      type: text
      label: THEME.ADMIN.HIT_DETAIL.SUMMARY_REPLACE_NEWLINE.LABEL
      help: THEME.ADMIN.HIT_DETAIL.SUMMARY_REPLACE_NEWLINE.HELP
      validate:
        type: text

    hit_detail.reference_system_link:
      type: text
      label: THEME.ADMIN.HIT_DETAIL.REFERENCE_SYSTEM_LINK.LABEL
      help: THEME.ADMIN.HIT_DETAIL.REFERENCE_SYSTEM_LINK.HELP

    hit_detail.reference_system_link_replace:
      type: text
      label: THEME.ADMIN.HIT_DETAIL.REFERENCE_SYSTEM_LINK_REPLACE.LABEL
      help: THEME.ADMIN.HIT_DETAIL.REFERENCE_SYSTEM_LINK_REPLACE.HELP

    hit_detail.csw_enabled:
      type: toggle
      label: THEME.ADMIN.HIT_DETAIL.CSW_ENABLED.LABEL
      help: THEME.ADMIN.HIT_DETAIL.CSW_ENABLED.HELP
      highlight: 1
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool

    hit_detail.rdf_enabled:
      type: toggle
      label: THEME.ADMIN.HIT_DETAIL.RDF_ENABLED.LABEL
      help: THEME.ADMIN.HIT_DETAIL.RDF_ENABLED.HELP
      highlight: 1
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool

    hit_detail.time_in_description:
      type: toggle
      label: THEME.ADMIN.HIT_DETAIL.TIME_IN_DESCRIPTION.LABEL
      help: THEME.ADMIN.HIT_DETAIL.TIME_IN_DESCRIPTION.HELP
      highlight: 1
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool

    hit_detail.address_order:
      type: selectize
      label: THEME.ADMIN.HIT_DETAIL.ADDRESS_ORDER.LABEL
      help: THEME.ADMIN.HIT_DETAIL.ADDRESS_ORDER.HELP
      selectize:
        data-options@: '\Grav\Plugin\InGridGravPlugin::getAdminDetailSortAddressOptions'
      validate:
        type: commalist

    hit_detail.address_unlink:
      type: toggle
      label: THEME.ADMIN.HIT_DETAIL.ADDRESS_UNLINK.LABEL
      help: THEME.ADMIN.HIT_DETAIL.ADDRESS_UNLINK.HELP
      highlight: 1
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool

    hit_detail.contact_order:
      type: selectize
      label: THEME.ADMIN.HIT_DETAIL.CONTACT_ORDER.LABEL
      help: THEME.ADMIN.HIT_DETAIL.CONTACT_ORDER.HELP
      selectize:
        data-options@: '\Grav\Plugin\InGridGravPlugin::getAdminDetailContactOrderOptions'
      validate:
        type: commalist