form:
  fields:
    rss:
      type: fieldset
      title: THEME.ADMIN.RSS.RSS_FEED
      text: THEME.ADMIN.RSS.RSS_FEED_HELP
      fields:
        .feeds:
          type: list
          label: THEME.ADMIN.RSS.RSS_LABEL
          style: vertical
          controls: bottom
          collapsed: true
          default: [ ]
          fields:
            .url:
              type: text
              label: THEME.ADMIN.RSS.RSS_ENTRY_URL
            .summary:
              type: text
              label: THEME.ADMIN.RSS.RSS_ENTRY_DESCRIPTION
            .provider:
              type: text
              label: THEME.ADMIN.RSS.RSS_ENTRY_PROVIDER
            .lang:
              type: text
              label: THEME.ADMIN.RSS.RSS_ENTRY_LANG
            .category:
              type: text
              label: THEME.ADMIN.RSS.RSS_ENTRY_CATEGORY